version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    user: "0"

  influxdb:
    image: influxdb:2.0.5
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - /var/lib/influxdb2:/var/lib/influxdb2
    env_file: 
      - vars.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true

  python-cron:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: python-cron
    volumes:
      - /etc/localtime:/etc/localtime:ro  # 确保容器使用正确的时区
      - .:/app
    env_file:
      - vars.env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true

# 由于我们已经将 volumes 指向了宿主机的目录，下面的定义可以删除
# volumes:
#   grafana-storage: {}
#   influxdb-storage: {}
